Repository googleapis/nodejs-translate, pull requests merged in 2019-10, with the labels that each got.

#334 fix: hybrid glossary tutorial region tag
  samples/hybridGlossaries.js
Labels: cla: yes

#337 fix: use compatible version of google-gax
  package.json
Labels: cla: yes

#338 fix: hybrid glossaries
  samples/hybridGlossaries.js
Labels: cla: yes

#335 chore: update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  synth.metadata
Labels: cla: yes

#341 chore: update CONTRIBUTING.md and make releaseType node
  .github/release-please.yml
  CONTRIBUTING.md
Labels: cla: yes

#340 fix: add filter to method signature
  protos/google/cloud/translate/v3beta1/translation_service.proto
  protos/protos.json
  synth.metadata
Labels: cla: yes, kokoro:force-run

#324 chore: release 4.2.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending, cla: yes, type: process

#344 chore: clean up eslint config
  samples/.eslintrc.yml
  samples/package.json
  samples/test/.eslintrc.yml
  samples/test/v3beta1/.eslintrc.yml
Labels: cla: yes

#345 fix(deps): bump google-gax to 1.7.5
  package.json
Labels: cla: yes

#347 fix: Remove extra brace in snippet
  samples/quickstart.js
Labels: cla: yes

#350 docs: spacing change in README
  README.md
  synth.metadata
Labels: cla: yes

#355 feat!: v3 is now the default API surface
  .bots/header-checker-lint.json
  package.json
  protos/google/cloud/translate/v3/translation_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  samples/package.json
  samples/quickstart.js
  samples/test/quickstart.test.js
  samples/test/translate.test.js
  samples/test/v3/translate_batch_translate_text.test.js
  samples/test/v3/translate_batch_translate_text_with_glossary.test.js
  samples/test/v3/translate_batch_translate_text_with_glossary_and_model.test.js
  samples/test/v3/translate_batch_translate_text_with_model.test.js
  samples/test/v3/translate_create_glossary.test.js
  samples/test/v3/translate_delete_glossary.test.js
  samples/test/v3/translate_detect_language.test.js
  samples/test/v3/translate_get_glossary.test.js
  samples/test/v3/translate_get_supported_languages.test.js
  samples/test/v3/translate_get_supported_languages_for_targets.test.js
  samples/test/v3/translate_list_codes.test.js
  samples/test/v3/translate_list_glossary.test.js
  samples/test/v3/translate_list_language_names.test.js
  samples/test/v3/translate_translate_text.test.js
  samples/test/v3/translate_translate_text_with_glossary.test.js
  samples/test/v3/translate_translate_text_with_glossary_and_model.test.js
  samples/test/v3/translate_translate_text_with_model.test.js
  samples/translate.js
  samples/v3/translate_batch_translate_text.js
  samples/v3/translate_batch_translate_text_with_glossary.js
  samples/v3/translate_batch_translate_text_with_glossary_and_model.js
  samples/v3/translate_batch_translate_text_with_model.js
  samples/v3/translate_create_glossary.js
  samples/v3/translate_delete_glossary.js
  samples/v3/translate_detect_language.js
  samples/v3/translate_get_glossary.js
  samples/v3/translate_get_supported_languages.js
  samples/v3/translate_get_supported_languages_for_target.js
  samples/v3/translate_list_codes.js
  samples/v3/translate_list_glossary.js
  samples/v3/translate_list_language_names.js
  samples/v3/translate_translate_text.js
  samples/v3/translate_translate_text_with_glossary.js
  samples/v3/translate_translate_text_with_glossary_and_model.js
  samples/v3/translate_translate_text_with_model.js
  src/index.ts
  src/v3/index.ts
  src/v3/translation_service_client.ts
  src/v3/translation_service_client_config.json
  src/v3/translation_service_proto_list.json
  system-test/translate.ts
  test/gapic-translation_service-v3.ts
  test/index.ts
  tsconfig.json
  tslint.json
Labels: cla: yes

#361 fix: package.json in build/ caused bad publish
  src/v3/translation_service_client.ts
Labels: cla: yes

#363 test: label v3 batch_translate test as flaky
  samples/test/v3/translate_batch_translate_text_with_glossary.test.js
  samples/test/v3/translate_list_glossary.test.js
Labels: cla: yes

#366 fix: flaky v3 tests
  samples/test/v3/translate_batch_translate_text_with_glossary.test.js
  samples/test/v3/translate_batch_translate_text_with_glossary_and_model.test.js
  samples/test/v3/translate_create_glossary.test.js
  samples/test/v3/translate_delete_glossary.test.js
  samples/test/v3/translate_get_glossary.test.js
  samples/test/v3/translate_list_glossary.test.js
  samples/test/v3/translate_translate_text_with_glossary.test.js
  samples/test/v3/translate_translate_text_with_glossary_and_model.test.js
Labels: cla: yes

#367 fix: region tag
  samples/v3/translate_translate_text_with_model.js
Labels: cla: yes
