Repository googleapis/nodejs-translate, pull requests merged in 2019-05, with the labels that each got.

#245 chore: update code formatting
  src/v3beta1/translation_service_client.js
  synth.metadata
Labels: :rotating_light:, automerge, cla: yes

#250 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#249 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#251 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#255 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#256 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#257 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#254 build: switches to piping coverage to codecov from Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#238 docs(samples): Translate with automl model sample
  samples/README.md
  samples/package.json
  samples/test/v3beta1/translate_translate_text_with_model_beta.test.js
  samples/v3beta1/translate_translate_text_with_model_beta.js
Labels: :rotating_light:, cla: yes

#259 fix: DEADLINE_EXCEEDED is no longer retried
  src/v3beta1/translation_service_client_config.json
  synth.metadata
Labels: cla: yes

#264 fix: DEADLINE_EXCEEDED is idempotent
  src/v3beta1/translation_service_client_config.json
  synth.metadata
Labels: cla: yes

#266 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#269 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#273 chore: release 4.0.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#268 docs: generate new samples/README.md, README.md
  .cloud-repo-tools.json
  .readme-partials.yml
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/package.json
  samples/quickstart.js
  synth.metadata
Labels: cla: yes

#276 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#278 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#275 refactor: drop dependency on lodash.merge and update links
  README.md
  samples/README.md
  src/v3beta1/translation_service_client.js
  synth.metadata
Labels: cla: yes

#282 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#283 docs: include section on beta samples in README
  samples/README.md
  synth.metadata
Labels: cla: yes

#284 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes

#277 fix(types): use Metadata types for apiResponse
  src/v2/index.ts
Labels: cla: yes

#285 feat: support apiEndpoint override
  package.json
  src/v2/index.ts
  test/index.ts
Labels: cla: yes
