Repository googleapis/nodejs-translate, pull requests merged in 2020-07, with the labels that each got.

#554 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#553 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#558 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#556 build: typo in gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full, gitattribute.*, in

#561 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#563 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#562 build: missing parenthesis in publish script, delete Node 8 tests, add config for cloud-rad for nodejs
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#564 build: move gitatrtributes files to node templates, rename __toc to toc
  .gitattributes
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#567 samples: translate --> fixes timeout issue
  samples/test/v3/translate_batch_translate_text_with_glossary_and_model.test.js
Labels: cla: yes

#569 docs: corrects spelling of build dependency adds backticks in docstring
  protos/google/cloud/translate/v3/translation_service.proto
  protos/google/cloud/translate/v3beta1/translation_service.proto
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: partial

#570 docs: add links to the CHANGELOG from the README.md for Java and Node
  .kokoro/release/docs-devsite.cfg
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial
