Repository googleapis/nodejs-translate, pull requests merged in 2020-02, with the labels that each got.

#433 chore: skip img.shields.io in docs test
  linkinator.config.json
Labels: cla: yes

#432 test: modernize mocha config
  .mocharc.json
  package.json
  test/mocha.opts
Labels: cla: yes

#437 chore: remove header check ignore and clang
  .bots/header-checker-lint.json
  .clang-format
Labels: cla: yes

#441 fix: pass x-goog-request-params header for streaming calls
  .gitignore
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
  test/gapic-translation_service-v3.ts
  test/gapic-translation_service-v3beta1.ts
Labels: cla: yes

#446 build: add GitHub actions config for unit tests
  .github/workflows/ci.yaml
  package.json
Labels: cla: yes

#452 build: add publish.yml enabling GitHub app for publishes
  .github/publish.yml
Labels: automerge, cla: yes

#451 feat: export protos in src/index.ts
  src/index.ts
Labels: automerge, cla: yes, kokoro:force-run

#455 chore: update jsdoc.js
  .jsdoc.js
Labels: automerge, cla: yes

#457 chore: correct .jsdoc.js protos and double quotes
  .jsdoc.js
Labels: automerge, cla: yes

#459 chore: update jsdoc with macro license
  .jsdoc.js
Labels: automerge, cla: yes
