Repository googleapis/nodejs-translate, pull requests merged in 2020-08, with the labels that each got.

#571 samples: increased timeout on batch_translate
  samples/test/v3beta1/translate_batch_translate_text_beta.test.js
Labels: cla: yes

#572 build: --credential-file-override is no longer required
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#573 build: use gapic-generator-typescript v1.0.7.
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
Labels: cla: yes, context: full
