Repository googleapis/nodejs-translate, pull requests merged in 2020-11, with the labels that each got.

#590 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: api: translate, cla: yes, context: full

#593 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: translate, automerge, cla: yes

#598 fix(browser): check for fetch on window
  protos/protos.json
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
Labels: api: translate, cla: yes, context: none

#601 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: translate, cla: yes, context: full
