Repository googleapis/nodejs-translate, pull requests merged in 2020-09, with the labels that each got.

#578 build: update config for node12
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#581 build: update test configuration
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: api: translate, cla: yes, context: none

#582 docs(terminology): update language to follow recommendations
  samples/translate.js
Labels: automerge, cla: yes
