Repository googleapis/nodejs-translate, pull requests merged in 2020-10, with the labels that each got.

#584 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#585 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: translate, automerge: exact, cla: yes, context: full

#587 samples(tests): added retry logic to flaky batch tests
  samples/test/v3/translate_batch_translate_text.test.js
  samples/test/v3/translate_batch_translate_text_with_glossary.test.js
  samples/test/v3/translate_batch_translate_text_with_glossary_and_model.test.js
  samples/test/v3/translate_batch_translate_text_with_model.test.js
Labels: cla: yes

#589 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
