Repository googleapis/nodejs-translate, pull requests merged in 2020-06, with the labels that each got.

#536 chore: updates to protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: cla: yes, context: none

#546 fix(samples): typo in CLI invocation
  samples/automl/automlTranslationDataset.js
Labels: cla: yes

#543 build(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#547 fix: handle fallback option properly
  .kokoro/populate-secrets.sh
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#549 test: ensure glossaryId in sample tests is unique
  samples/test/v3beta1/translate_list_glossary_beta.test.js
Labels: automerge, cla: yes

#551 fix: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#552 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
