Repository googleapis/nodejs-translate, pull requests merged in 2020-05, with the labels that each got.

#531 feat: check status of long running operation by its name; fix linting
  protos/protos.js
  samples/automl/automlTranslationDataset.js
  samples/automl/automlTranslationModel.js
  samples/automl/automlTranslationPredict.js
  src/v3/translation_service_client.ts
  src/v3beta1/translation_service_client.ts
  synth.metadata
  system-test/translate.ts
  test/gapic_translation_service_v3.ts
  test/gapic_translation_service_v3beta1.ts
  test/index.ts
Labels: automerge, cla: yes

#532 chore: linting
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#533 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
