Repository googleapis/nodejs-translate, pull requests merged in 2021-04, with the labels that each got.

#637 test: ensure output dir is empty
  samples/test/v3/translate_batch_translate_text_with_glossary.test.js
Labels: api: translate, cla: yes

#638 build: compile-protos should be part of prepare
  package.json
Labels: api: translate, automerge, cla: yes

#639 feat: added v3beta1 proto for online and batch document translation
  protos/google/cloud/translate/v3beta1/translation_service.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v3beta1/gapic_metadata.json
  src/v3beta1/translation_service_client.ts
  src/v3beta1/translation_service_client_config.json
  synth.metadata
  test/gapic_translation_service_v3beta1.ts
Labels: api: translate, cla: yes, context: full

#647 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  .repo-metadata.json
  owlbot.py
  synth.metadata
Labels: api: translate, cla: yes

#642 chore: Add title back into Readme
  .readme-partials.yml
  README.md
  samples/README.md
Labels: api: translate, cla: yes
